import 'package:again_islami/moduels/layout/quran/widget/recent_data.dart';
import 'package:again_islami/moduels/layout/quran/widget/sura_data.dart';
import 'package:flutter/foundation.dart';

class SettingProvider extends ChangeNotifier {

  List <RecentData> _recentData =[
    RecentData(nameAR: 'الأنبياء', nameEN:  'Al-Anbiya', verses: '112 Verses'),
    RecentData(nameAR: 'الفاتحه', nameEN:  'Al-Fatiha', verses: '7 Verses'),
  ];

  List<SuraData> _suraData = [
    SuraData(id: 1, nameAR: "الفاتحه", nameEN: "Al-Fatiha", verses: '7'),
    SuraData(id: 2, nameAR: "البقرة", nameEN: "Al-Baqarah", verses: '286'),
    SuraData(id: 3, nameAR: "آل عمران", nameEN: "Aal-E-Imran", verses: '200'),
    SuraData(id: 4, nameAR: "النساء", nameEN: "An-Nisa'", verses: '176'),
    SuraData(id: 5, nameAR: "المائدة", nameEN: "Al-Ma'idah", verses: '120'),
    SuraData(id: 6, nameAR: "الأنعام", nameEN: "Al-An'am", verses: '165'),
    SuraData(id: 7, nameAR: "الأعراف", nameEN: "Al-A'raf", verses: '206'),
    SuraData(id: 8, nameAR: "الأنفال", nameEN: "Al-Anfal", verses: '75'),
    SuraData(id: 9, nameAR: "التوبة", nameEN: "At-Tawbah", verses: '129'),
    SuraData(id: 10, nameAR: "يونس", nameEN: "Yunus", verses: '109'),
    SuraData(id: 11, nameAR: "هود", nameEN: "Hud", verses: '123'),
    SuraData(id: 12, nameAR: "يوسف", nameEN: "Yusuf", verses: '111'),
    SuraData(id: 13, nameAR: "الرعد", nameEN: "Ar-Ra'd", verses: '43'),
    SuraData(id: 14, nameAR: "إبراهيم", nameEN: "Ibrahim", verses: '52'),
    SuraData(id: 15, nameAR: "الحجر", nameEN: "Al-Hijr", verses: '99'),
    SuraData(id: 16, nameAR: "النحل", nameEN: "An-Nahl", verses: '128'),
    SuraData(id: 17, nameAR: "الإسراء", nameEN: "Al-Isra", verses: '111'),
    SuraData(id: 18, nameAR: "الكهف", nameEN: "Al-Kahf", verses: '110'),
    SuraData(id: 19, nameAR: "مريم", nameEN: "Maryam", verses: '98'),
    SuraData(id: 20, nameAR: "طه", nameEN: "Ta-Ha", verses: '135'),
    SuraData(id: 21, nameAR: "الأنبياء", nameEN: "Al-Anbiya", verses: '112'),
    SuraData(id: 22, nameAR: "الحج", nameEN: "Al-Hajj", verses: '78'),
    SuraData(id: 23, nameAR: "المؤمنون", nameEN: "Al-Mu'minun", verses: '118'),
    SuraData(id: 24, nameAR: "النّور", nameEN: "An-Nur", verses: '64'),
    SuraData(id: 25, nameAR: "الفرقان", nameEN: "Al-Furqan", verses: '77'),
    SuraData(id: 26, nameAR: "الشعراء", nameEN: "Ash-Shu'ara", verses: '227'),
    SuraData(id: 27, nameAR: "النّمل", nameEN: "An-Naml", verses: '93'),
    SuraData(id: 28, nameAR: "القصص", nameEN: "Al-Qasas", verses: '88'),
    SuraData(id: 29, nameAR: "العنكبوت", nameEN: "Al-Ankabut", verses: '69'),
    SuraData(id: 30, nameAR: "الرّوم", nameEN: "Ar-Rum", verses: '60'),
    SuraData(id: 31, nameAR: "لقمان", nameEN: "Luqman", verses: '34'),
    SuraData(id: 32, nameAR: "السجدة", nameEN: "As-Sajda", verses: '30'),
    SuraData(id: 33, nameAR: "الأحزاب", nameEN: "Al-Ahzab", verses: '73'),
    SuraData(id: 34, nameAR: "سبأ", nameEN: "Saba", verses: '54'),
    SuraData(id: 35, nameAR: "فاطر", nameEN: "Fatir", verses: '45'),
    SuraData(id: 36, nameAR: "يس", nameEN: "Ya-Sin", verses: '83'),
    SuraData(id: 37, nameAR: "الصافات", nameEN: "As-Saffat", verses: '182'),
    SuraData(id: 38, nameAR: "ص", nameEN: "Sad", verses: '88'),
    SuraData(id: 39, nameAR: "الزمر", nameEN: "Az-Zumar", verses: '75'),
    SuraData(id: 40, nameAR: "غافر", nameEN: "Ghafir", verses: '85'),
    SuraData(id: 41, nameAR: "فصّلت", nameEN: "Fussilat", verses: '54'),
    SuraData(id: 42, nameAR: "الشورى", nameEN: "Ash-Shura", verses: '53'),
    SuraData(id: 43, nameAR: "الزخرف", nameEN: "Az-Zukhruf", verses: '89'),
    SuraData(id: 44, nameAR: "الدّخان", nameEN: "Ad-Dukhan", verses: '59'),
    SuraData(id: 45, nameAR: "الجاثية", nameEN: "Al-Jathiya", verses: '37'),
    SuraData(id: 46, nameAR: "الأحقاف", nameEN: "Al-Ahqaf", verses: '35'),
    SuraData(id: 47, nameAR: "محمد", nameEN: "Muhammad", verses: '38'),
    SuraData(id: 48, nameAR: "الفتح", nameEN: "Al-Fath", verses: '29'),
    SuraData(id: 49, nameAR: "الحجرات", nameEN: "Al-Hujurat", verses: '18'),
    SuraData(id: 50, nameAR: "ق", nameEN: "Qaf", verses: '45'),
    SuraData(id: 51, nameAR: "الذاريات", nameEN: "Adh-Dhariyat", verses: '60'),
    SuraData(id: 52, nameAR: "الطور", nameEN: "At-Tur", verses: '49'),
    SuraData(id: 53, nameAR: "النجم", nameEN: "An-Najm", verses: '62'),
    SuraData(id: 54, nameAR: "القمر", nameEN: "Al-Qamar", verses: '55'),
    SuraData(id: 55, nameAR: "الرحمن", nameEN: "Ar-Rahman", verses: '78'),
    SuraData(id: 56, nameAR: "الواقعة", nameEN: "Al-Waqi'a", verses: '96'),
    SuraData(id: 57, nameAR: "الحديد", nameEN: "Al-Hadid", verses: '29'),
    SuraData(id: 58, nameAR: "المجادلة", nameEN: "Al-Mujadila", verses: '22'),
    SuraData(id: 59, nameAR: "الحشر", nameEN: "Al-Hashr", verses: '24'),
    SuraData(id: 60, nameAR: "الممتحنة", nameEN: "Al-Mumtahina", verses: '13'),
    SuraData(id: 61, nameAR: "الصف", nameEN: "As-Saff", verses: '11'),
    SuraData(id: 62, nameAR: "الجمعة", nameEN: "Al-Jumu'a", verses: '11'),
    SuraData(id: 63, nameAR: "المنافقون", nameEN: "Al-Munafiqun", verses: '11'),
    SuraData(id: 64, nameAR: "التغابن", nameEN: "At-Taghabun", verses: '18'),
    SuraData(id: 65, nameAR: "الطلاق", nameEN: "At-Talaq", verses: '12'),
    SuraData(id: 66, nameAR: "التحريم", nameEN: "At-Tahrim", verses: '12'),
    SuraData(id: 67, nameAR: "الملك", nameEN: "Al-Mulk", verses: '30'),
    SuraData(id: 68, nameAR: "القلم", nameEN: "Al-Qalam", verses: '52'),
    SuraData(id: 69, nameAR: "الحاقة", nameEN: "Al-Haqqah", verses: '56'),
    SuraData(id: 70, nameAR: "المعارج", nameEN: "Al-Ma'arij", verses: '44'),
    SuraData(id: 71, nameAR: "نوح", nameEN: "Nuh", verses: '28'),
    SuraData(id: 72, nameAR: "الجن", nameEN: "Al-Jinn", verses: '28'),
    SuraData(id: 73, nameAR: "المزّمّل", nameEN: "Al-Muzzammil", verses: '20'),
    SuraData(id: 74, nameAR: "المدّثر", nameEN: "Al-Muddathir", verses: '56'),
    SuraData(id: 75, nameAR: "القيامة", nameEN: "Al-Qiyamah", verses: '40'),
    SuraData(id: 76, nameAR: "الإنسان", nameEN: "Al-Insan", verses: '31'),
    SuraData(id: 77, nameAR: "المرسلات", nameEN: "Al-Mursalat", verses: '50'),
    SuraData(id: 78, nameAR: "النبأ", nameEN: "An-Naba'", verses: '40'),
    SuraData(id: 79, nameAR: "النازعات", nameEN: "An-Nazi'at", verses: '46'),
    SuraData(id: 80, nameAR: "عبس", nameEN: "Abasa", verses: '42'),
    SuraData(id: 81, nameAR: "التكوير", nameEN: "At-Takwir", verses: '29'),
    SuraData(id: 82, nameAR: "الإنفطار", nameEN: "Al-Infitar", verses: '19'),
    SuraData(id: 83, nameAR: "المطفّفين", nameEN: "Al-Mutaffifin", verses: '36'),
    SuraData(id: 84, nameAR: "الإنشقاق", nameEN: "Al-Inshiqaq", verses: '25'),
    SuraData(id: 85, nameAR: "البروج", nameEN: "Al-Buruj", verses: '22'),
    SuraData(id: 86, nameAR: "الطارق", nameEN: "At-Tariq", verses: '17'),
    SuraData(id: 87, nameAR: "الأعلى", nameEN: "Al-A'la", verses: '19'),
    SuraData(id: 88, nameAR: "الغاشية", nameEN: "Al-Ghashiyah", verses: '26'),
    SuraData(id: 89, nameAR: "الفجر", nameEN: "Al-Fajr", verses: '30'),
    SuraData(id: 90, nameAR: "البلد", nameEN: "Al-Balad", verses: '20'),
    SuraData(id: 91, nameAR: "الشمس", nameEN: "Ash-Shams", verses: '15'),
    SuraData(id: 92, nameAR: "الليل", nameEN: "Al-Lail", verses: '21'),
    SuraData(id: 93, nameAR: "الضحى", nameEN: "Ad-Duha", verses: '11'),
    SuraData(id: 94, nameAR: "الشرح", nameEN: "Ash-Sharh", verses: '8'),
    SuraData(id: 95, nameAR: "التين", nameEN: "At-Tin", verses: '8'),
    SuraData(id: 96, nameAR: "العلق", nameEN: "Al-Alaq", verses: '19'),
    SuraData(id: 97, nameAR: "القدر", nameEN: "Al-Qadr", verses: '5'),
    SuraData(id: 98, nameAR: "البينة", nameEN: "Al-Bayyina", verses: '8'),
    SuraData(id: 99, nameAR: "الزلزلة", nameEN: "Az-Zalzalah", verses: '8'),
    SuraData(id: 100, nameAR: "العاديات", nameEN: "Al-Adiyat", verses: '11'),
    SuraData(id: 101, nameAR: "القارعة", nameEN: "Al-Qari'a", verses: '11'),
    SuraData(id: 102, nameAR: "التكاثر", nameEN: "At-Takathur", verses: '8'),
    SuraData(id: 103, nameAR: "العصر", nameEN: "Al-Asr", verses: '3'),
    SuraData(id: 104, nameAR: "الهمزة", nameEN: "Al-Humazah", verses: '9'),
    SuraData(id: 105, nameAR: "الفيل", nameEN: "Al-Fil", verses: '5'),
    SuraData(id: 106, nameAR: "قريش", nameEN: "Quraysh", verses: '4'),
    SuraData(id: 107, nameAR: "الماعون", nameEN: "Al-Ma'un", verses: '7'),
    SuraData(id: 108, nameAR: "الكوثر", nameEN: "Al-Kawthar", verses: '3'),
    SuraData(id: 109, nameAR: "الكافرون", nameEN: "Al-Kafirun", verses: '6'),
    SuraData(id: 110, nameAR: "النصر", nameEN: "An-Nasr", verses: '3'),
    SuraData(id: 111, nameAR: "المسد", nameEN: "Al-Masad", verses: '5'),
    SuraData(id: 112, nameAR: "الإخلاص", nameEN: "Al-Ikhlas", verses: '4'),
    SuraData(id: 113, nameAR: "الفلق", nameEN: "Al-Falaq", verses: '5'),
    SuraData(id: 114, nameAR: "الناس", nameEN: "An-Nas", verses: '6'),
  ];



  List<SuraData> get suraData => _suraData ;
  List<RecentData> get recentData => _recentData ;
}
